# 第二章：结合金融场景演示Numpy模块编程

## 2.1 从一个投资案例讲起

In [1]:
return_May25=[-0.035099,-0.013892,0.005848,0.021242]
weight_list=[0.15,0.2,0.25,0.4]
n=len(weight_list)

In [2]:
return_weight=[]
for i in range(n):
    return_weight.append(return_May25[i]*weight_list[i])
return_port_May25=sum(return_weight)
print('2020年5月25日投资组合的收益率',round(return_port_May25,6))

2020年5月25日投资组合的收益率 0.001916


In [3]:
import numpy as np
np.__version__

'1.24.3'

## 2.2 N维数组

In [4]:
# 1.直接输入法
weight_array1=np.array([0.15,0.2,0.25,0.4])
type(weight_array1)

numpy.ndarray

In [5]:
weight_array1.shape

(4,)

In [6]:
return_array1=np.array([
[-0.035099,0.17230,-0.003450,-0.024551,0.039368],
[-0.013892,0.024334,-0.033758,0.014622,0.000128],
[0.005848,-0.02907,0.005831,0.005797,-0.005764],
[0.021242,0.002133,-0.029803,-0.002743,-0.014301]])
return_array1.shape

(4, 5)

In [8]:
# 2.将列表转化为数组
return_list=[
-0.035099,0.17230,-0.003450,-0.024551,0.039368,
-0.013892,0.024334,-0.033758,0.014622,0.000128,
0.005848,-0.02907,0.005831,0.005797,-0.005764,
0.021242,0.002133,-0.029803,-0.002743,-0.014301]
return_array2=np.array(return_list)
return_array2=return_array2.reshape(4,5)
return_array2

array([[-3.5099e-02,  1.7230e-01, -3.4500e-03, -2.4551e-02,  3.9368e-02],
       [-1.3892e-02,  2.4334e-02, -3.3758e-02,  1.4622e-02,  1.2800e-04],
       [ 5.8480e-03, -2.9070e-02,  5.8310e-03,  5.7970e-03, -5.7640e-03],
       [ 2.1242e-02,  2.1330e-03, -2.9803e-02, -2.7430e-03, -1.4301e-02]])

In [9]:
# 3.查看数组的属性
weight_array2=np.array(weight_list)
weight_array2

array([0.15, 0.2 , 0.25, 0.4 ])

In [10]:
return_array3=return_array2.ravel() #将二维数组降至一维
return_array3

array([-3.5099e-02,  1.7230e-01, -3.4500e-03, -2.4551e-02,  3.9368e-02,
       -1.3892e-02,  2.4334e-02, -3.3758e-02,  1.4622e-02,  1.2800e-04,
        5.8480e-03, -2.9070e-02,  5.8310e-03,  5.7970e-03, -5.7640e-03,
        2.1242e-02,  2.1330e-03, -2.9803e-02, -2.7430e-03, -1.4301e-02])

In [11]:
weight_array1.ndim

1

In [12]:
return_array1.ndim

2

In [13]:
weight_array1.size

4

In [14]:
return_array1.size

20

In [15]:
weight_array1.dtype

dtype('float64')

In [16]:
return_array1.dtype

dtype('float64')

In [18]:
# 整数数列的数组
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b=np.arange(1,18,3)
b

array([ 1,  4,  7, 10, 13, 16])

In [22]:
c=np.linspace(0,100,51)
c

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

In [23]:
len(c)

51

In [24]:
# 3.元素为0的数组
zero_array1=np.zeros(8)
zero_array1

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
zero_array2=np.zeros((5,7))
zero_array2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [27]:
zero_weight=np.zeros_like(weight_array1)
zero_weight

array([0., 0., 0., 0.])

In [28]:
zero_return=np.zeros_like(return_array1)
zero_return

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
one_weight=np.ones_like(weight_array1)
one_weight

array([1., 1., 1., 1.])

In [30]:
one_return=np.ones_like(return_array1)
one_return

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
d=np.eye(6)
d

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## 2.3 数组的相关功能

In [33]:
return_array1[1,3]

0.014622

In [35]:
np.where(return_array1>0.014)

(array([0, 0, 1, 1, 3], dtype=int64), array([1, 4, 1, 3, 0], dtype=int64))

In [36]:
return_array1[1:3,1:4]

array([[ 0.024334, -0.033758,  0.014622],
       [-0.02907 ,  0.005831,  0.005797]])

In [37]:
return_array1[1]

array([-0.013892,  0.024334, -0.033758,  0.014622,  0.000128])

In [38]:
return_array1[:2]

array([[-3.5099e-02,  1.7230e-01, -3.4500e-03, -2.4551e-02,  3.9368e-02],
       [-1.3892e-02,  2.4334e-02, -3.3758e-02,  1.4622e-02,  1.2800e-04]])

In [39]:
np.sort(return_array1,axis=0)

array([[-3.5099e-02, -2.9070e-02, -3.3758e-02, -2.4551e-02, -1.4301e-02],
       [-1.3892e-02,  2.1330e-03, -2.9803e-02, -2.7430e-03, -5.7640e-03],
       [ 5.8480e-03,  2.4334e-02, -3.4500e-03,  5.7970e-03,  1.2800e-04],
       [ 2.1242e-02,  1.7230e-01,  5.8310e-03,  1.4622e-02,  3.9368e-02]])

In [40]:
np.sort(return_array1,axis=1)

array([[-3.5099e-02, -2.4551e-02, -3.4500e-03,  3.9368e-02,  1.7230e-01],
       [-3.3758e-02, -1.3892e-02,  1.2800e-04,  1.4622e-02,  2.4334e-02],
       [-2.9070e-02, -5.7640e-03,  5.7970e-03,  5.8310e-03,  5.8480e-03],
       [-2.9803e-02, -1.4301e-02, -2.7430e-03,  2.1330e-03,  2.1242e-02]])

In [41]:
np.sort(return_array1)

array([[-3.5099e-02, -2.4551e-02, -3.4500e-03,  3.9368e-02,  1.7230e-01],
       [-3.3758e-02, -1.3892e-02,  1.2800e-04,  1.4622e-02,  2.4334e-02],
       [-2.9070e-02, -5.7640e-03,  5.7970e-03,  5.8310e-03,  5.8480e-03],
       [-2.9803e-02, -1.4301e-02, -2.7430e-03,  2.1330e-03,  2.1242e-02]])

In [44]:
return_BOC=np.array([0.005848,-0.002907,0.005831,0.005797,-0.005764])
return_SAIC=np.array([0.021242,-0.002133,-0.029803,-0.002743,-0.014301])
return_2stock=np.append([return_BOC],[return_SAIC],axis=0)
return_2stock

array([[ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764],
       [ 0.021242, -0.002133, -0.029803, -0.002743, -0.014301]])

In [46]:
return_2stock_new1=np.append([return_BOC],[return_SAIC],axis=1)
return_2stock_new1

array([[ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764,  0.021242,
        -0.002133, -0.029803, -0.002743, -0.014301]])

In [47]:
return_2stock_new2=np.append([return_BOC],[return_SAIC])
return_2stock_new2

array([ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764,  0.021242,
       -0.002133, -0.029803, -0.002743, -0.014301])

In [48]:
return_CAST=np.array([-0.035099,0.017230,-0.003450,-0.024551,0.039368])
return_CSS=np.array([-0.013892,0.024334,-0.033758,0.014622,0.000128])
return_4stock=np.concatenate(([return_CAST],[return_CSS],[return_BOC],[return_SAIC]),axis=0)
return_4stock

array([[-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368],
       [-0.013892,  0.024334, -0.033758,  0.014622,  0.000128],
       [ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764],
       [ 0.021242, -0.002133, -0.029803, -0.002743, -0.014301]])

In [51]:
return_4stock_new1=np.concatenate(([return_CAST],[return_CSS],[return_BOC],[return_SAIC]),axis=1)
return_4stock_new1

array([[-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368, -0.013892,
         0.024334, -0.033758,  0.014622,  0.000128,  0.005848, -0.002907,
         0.005831,  0.005797, -0.005764,  0.021242, -0.002133, -0.029803,
        -0.002743, -0.014301]])

In [50]:
return_4stock_new2=np.concatenate(([return_CAST],[return_CSS],[return_BOC],[return_SAIC]))
return_4stock_new2

array([[-0.035099,  0.01723 , -0.00345 , -0.024551,  0.039368],
       [-0.013892,  0.024334, -0.033758,  0.014622,  0.000128],
       [ 0.005848, -0.002907,  0.005831,  0.005797, -0.005764],
       [ 0.021242, -0.002133, -0.029803, -0.002743, -0.014301]])

## 2.4 数组的相关运算

In [52]:
return_array1.sum(axis=0)  # 按列求和

array([-0.021901,  0.169697, -0.06118 , -0.006875,  0.019431])

In [53]:
return_array1.sum(axis=1) # 按行求和

array([ 0.148568, -0.008566, -0.017358, -0.023472])

In [54]:
return_array1.sum() # 全部元素之和

0.09917200000000002

In [55]:
return_array1.prod(axis=0)

array([ 6.05706573e-08, -2.59976845e-07, -2.02394557e-08,  5.70827745e-09,
        4.15378200e-10])

In [56]:
return_array1.prod(axis=1)

array([-2.01656235e-08,  2.13585486e-11,  3.31224696e-11, -5.29710348e-11])

In [57]:
return_array1.prod()

7.556915345169367e-40

In [58]:
return_array1.max(axis=0)

array([0.021242, 0.1723  , 0.005831, 0.014622, 0.039368])

In [59]:
return_array1.max(axis=1)

array([0.1723  , 0.024334, 0.005848, 0.021242])

In [60]:
return_array1.max()

0.1723

In [61]:
return_array1.min(axis=0)

array([-0.035099, -0.02907 , -0.033758, -0.024551, -0.014301])

In [62]:
return_array1.min(axis=1)

array([-0.035099, -0.033758, -0.02907 , -0.029803])

In [63]:
return_array1.min()

-0.035099

In [64]:
return_array1.mean(axis=0)

array([-0.00547525,  0.04242425, -0.015295  , -0.00171875,  0.00485775])

In [65]:
return_array1.mean(axis=1)

array([ 0.0297136, -0.0017132, -0.0034716, -0.0046944])

In [66]:
return_array1.mean()

0.004958600000000001

In [67]:
return_array1.var(axis=0)

array([0.00044761, 0.00598245, 0.00028449, 0.00021147, 0.0004233 ])

In [68]:
return_array1.var(axis=1)

array([0.00573385, 0.00042478, 0.00018397, 0.00028917])

In [69]:
return_array1.var()

0.0018633324640400003

In [70]:
return_array1.std(axis=0)

array([0.02115677, 0.07734627, 0.01686695, 0.0145419 , 0.0205743 ])

In [71]:
return_array1.std(axis=1)

array([0.07572217, 0.02061008, 0.01356343, 0.01700498])

In [72]:
return_array1.std()

0.043166334846034826

In [73]:
np.sqrt(return_array1)  # 这里由于存在负数，所以会存在报错

C:\Users\Zhang ZhiXin\AppData\Local\Temp\ipykernel_20036\2539222511.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(return_array1)


array([[       nan, 0.41509035,        nan,        nan, 0.19841371],
       [       nan, 0.15599359,        nan, 0.12092146, 0.01131371],
       [0.07647222,        nan, 0.07636098, 0.07613803,        nan],
       [0.14574636, 0.04618441,        nan,        nan,        nan]])

In [75]:
np.square(return_array1) # 对每个元素计算平方

array([[1.23193980e-03, 2.96872900e-02, 1.19025000e-05, 6.02751601e-04,
        1.54983942e-03],
       [1.92987664e-04, 5.92143556e-04, 1.13960256e-03, 2.13802884e-04,
        1.63840000e-08],
       [3.41991040e-05, 8.45064900e-04, 3.40005610e-05, 3.36052090e-05,
        3.32236960e-05],
       [4.51222564e-04, 4.54968900e-06, 8.88218809e-04, 7.52404900e-06,
        2.04518601e-04]])

In [76]:
np.exp(return_array1) # 对每一个元素计算以e为底的指数次方

array([[0.96550983, 1.18803419, 0.99655594, 0.97574792, 1.04015319],
       [0.98620405, 1.02463249, 0.96680544, 1.01472942, 1.00012801],
       [1.00586513, 0.97134847, 1.00584803, 1.00581384, 0.99425258],
       [1.02146922, 1.00213528, 0.97063673, 0.99726076, 0.98580077]])

In [77]:
np.log(return_array1)  # 对每个元素计算自然对数

C:\Users\Zhang ZhiXin\AppData\Local\Temp\ipykernel_20036\2476508234.py:1: RuntimeWarning: invalid value encountered in log
  np.log(return_array1)  # 对每个元素计算自然对数


array([[        nan, -1.75851814,         nan,         nan, -3.23480198],
       [        nan, -3.71588073,         nan, -4.22522804, -8.96348029],
       [-5.14165556,         nan, -5.14456677, -5.15041474,         nan],
       [-3.85177493, -6.15022584,         nan,         nan,         nan]])

In [78]:
np.log2(return_array1)

C:\Users\Zhang ZhiXin\AppData\Local\Temp\ipykernel_20036\2588867951.py:1: RuntimeWarning: invalid value encountered in log2
  np.log2(return_array1)


array([[         nan,  -2.53700539,          nan,          nan,
         -4.66683277],
       [         nan,  -5.3608827 ,          nan,  -6.09571553,
        -12.93156857],
       [ -7.41784097,          nan,  -7.42204096,  -7.4304778 ,
                 nan],
       [ -5.55693658,  -8.87290032,          nan,          nan,
                 nan]])

In [79]:
np.log10(return_array1)

C:\Users\Zhang ZhiXin\AppData\Local\Temp\ipykernel_20036\3084611911.py:1: RuntimeWarning: invalid value encountered in log10
  np.log10(return_array1)


array([[        nan, -0.76371472,         nan,         nan, -1.40485665],
       [        nan, -1.6137865 ,         nan, -1.83499322, -3.89279003],
       [-2.23299264,         nan, -2.23425696, -2.2367967 ,         nan],
       [-1.6728046 , -2.67100914,         nan,         nan,         nan]])

In [80]:
np.log1p(return_array1) # 对（1+每个元素）计算自然对数

array([[-3.57297736e-02,  1.58967631e-01, -3.45596497e-03,
        -2.48574012e-02,  3.86128361e-02],
       [-1.39893969e-02,  2.40426453e-02, -3.43409585e-02,
         1.45161293e-02,  1.27991809e-04],
       [ 5.83096682e-03, -2.95009039e-02,  5.81406552e-03,
         5.78026205e-03, -5.78067596e-03],
       [ 2.10195336e-02,  2.13072839e-03, -3.02561353e-02,
        -2.74676892e-03, -1.44042448e-02]])

In [81]:
new_array1=return_array1+one_return 
new_array1

array([[0.964901, 1.1723  , 0.99655 , 0.975449, 1.039368],
       [0.986108, 1.024334, 0.966242, 1.014622, 1.000128],
       [1.005848, 0.97093 , 1.005831, 1.005797, 0.994236],
       [1.021242, 1.002133, 0.970197, 0.997257, 0.985699]])

In [82]:
new_array2=return_array1-one_return
new_array2

array([[-1.035099, -0.8277  , -1.00345 , -1.024551, -0.960632],
       [-1.013892, -0.975666, -1.033758, -0.985378, -0.999872],
       [-0.994152, -1.02907 , -0.994169, -0.994203, -1.005764],
       [-0.978758, -0.997867, -1.029803, -1.002743, -1.014301]])

In [84]:
new_array3=return_array1*new_array2
new_array3

array([[ 3.63309398e-02, -1.42612710e-01,  3.46190250e-03,
         2.51537516e-02, -3.78181606e-02],
       [ 1.40849877e-02, -2.37418564e-02,  3.48976026e-02,
        -1.44081971e-02, -1.27983616e-04],
       [-5.81380090e-03,  2.99150649e-02, -5.79699944e-03,
        -5.76339479e-03,  5.79722370e-03],
       [-2.07907774e-02, -2.12845031e-03,  3.06912188e-02,
         2.75052405e-03,  1.45055186e-02]])

In [85]:
new_array4=new_array1/new_array2
new_array4

array([[-0.93218233, -1.41633442, -0.99312372, -0.95207462, -1.08196271],
       [-0.97259669, -1.04988182, -0.93468878, -1.02967795, -1.00025603],
       [-1.0117648 , -0.94350239, -1.0117304 , -1.0116616 , -0.98853807],
       [-1.04340603, -1.00427512, -0.94211903, -0.99452901, -0.97180127]])

In [86]:
new_array5=new_array1**new_array2
new_array5

array([[1.03767627, 0.87671132, 1.00347391, 1.02579475, 0.96358678],
       [1.0142848 , 0.9768154 , 1.0361379 , 0.98579794, 0.99987203],
       [0.9942199 , 1.03082401, 0.99423651, 0.99426973, 1.00583093],
       [0.97963714, 0.99787608, 1.03164835, 1.0027581 , 1.01471749]])

In [87]:
new_array6=pow(new_array1,new_array2)
new_array6

array([[1.03767627, 0.87671132, 1.00347391, 1.02579475, 0.96358678],
       [1.0142848 , 0.9768154 , 1.0361379 , 0.98579794, 0.99987203],
       [0.9942199 , 1.03082401, 0.99423651, 0.99426973, 1.00583093],
       [0.97963714, 0.99787608, 1.03164835, 1.0027581 , 1.01471749]])

In [88]:
new_array7=new_array6+np.array([1,0,1,0,1])
new_array7

array([[2.03767627, 0.87671132, 2.00347391, 1.02579475, 1.96358678],
       [2.0142848 , 0.9768154 , 2.0361379 , 0.98579794, 1.99987203],
       [1.9942199 , 1.03082401, 1.99423651, 0.99426973, 2.00583093],
       [1.97963714, 0.99787608, 2.03164835, 1.0027581 , 2.01471749]])

In [89]:
new_array8=return_array1+1
new_array8

array([[0.964901, 1.1723  , 0.99655 , 0.975449, 1.039368],
       [0.986108, 1.024334, 0.966242, 1.014622, 1.000128],
       [1.005848, 0.97093 , 1.005831, 1.005797, 0.994236],
       [1.021242, 1.002133, 0.970197, 0.997257, 0.985699]])

In [91]:
new_array9=return_array1-1
new_array9

array([[-1.035099, -0.8277  , -1.00345 , -1.024551, -0.960632],
       [-1.013892, -0.975666, -1.033758, -0.985378, -0.999872],
       [-0.994152, -1.02907 , -0.994169, -0.994203, -1.005764],
       [-0.978758, -0.997867, -1.029803, -1.002743, -1.014301]])

In [92]:
new_array10=return_array1*2
new_array10

array([[-7.0198e-02,  3.4460e-01, -6.9000e-03, -4.9102e-02,  7.8736e-02],
       [-2.7784e-02,  4.8668e-02, -6.7516e-02,  2.9244e-02,  2.5600e-04],
       [ 1.1696e-02, -5.8140e-02,  1.1662e-02,  1.1594e-02, -1.1528e-02],
       [ 4.2484e-02,  4.2660e-03, -5.9606e-02, -5.4860e-03, -2.8602e-02]])

In [93]:
new_array11=return_array1/2
new_array11

array([[-1.75495e-02,  8.61500e-02, -1.72500e-03, -1.22755e-02,
         1.96840e-02],
       [-6.94600e-03,  1.21670e-02, -1.68790e-02,  7.31100e-03,
         6.40000e-05],
       [ 2.92400e-03, -1.45350e-02,  2.91550e-03,  2.89850e-03,
        -2.88200e-03],
       [ 1.06210e-02,  1.06650e-03, -1.49015e-02, -1.37150e-03,
        -7.15050e-03]])

In [94]:
new_array12=return_array1**2
new_array12

array([[1.23193980e-03, 2.96872900e-02, 1.19025000e-05, 6.02751601e-04,
        1.54983942e-03],
       [1.92987664e-04, 5.92143556e-04, 1.13960256e-03, 2.13802884e-04,
        1.63840000e-08],
       [3.41991040e-05, 8.45064900e-04, 3.40005610e-05, 3.36052090e-05,
        3.32236960e-05],
       [4.51222564e-04, 4.54968900e-06, 8.88218809e-04, 7.52404900e-06,
        2.04518601e-04]])

In [95]:
new_array13=pow(return_array1,2)
new_array13

array([[1.23193980e-03, 2.96872900e-02, 1.19025000e-05, 6.02751601e-04,
        1.54983942e-03],
       [1.92987664e-04, 5.92143556e-04, 1.13960256e-03, 2.13802884e-04,
        1.63840000e-08],
       [3.41991040e-05, 8.45064900e-04, 3.40005610e-05, 3.36052090e-05,
        3.32236960e-05],
       [4.51222564e-04, 4.54968900e-06, 8.88218809e-04, 7.52404900e-06,
        2.04518601e-04]])

In [96]:
return_max=np.maximum(return_array1,return_array2)
return_max

array([[-3.5099e-02,  1.7230e-01, -3.4500e-03, -2.4551e-02,  3.9368e-02],
       [-1.3892e-02,  2.4334e-02, -3.3758e-02,  1.4622e-02,  1.2800e-04],
       [ 5.8480e-03, -2.9070e-02,  5.8310e-03,  5.7970e-03, -5.7640e-03],
       [ 2.1242e-02,  2.1330e-03, -2.9803e-02, -2.7430e-03, -1.4301e-02]])

In [98]:
return_min=np.minimum(return_array1,zero_return)
return_min

array([[-0.035099,  0.      , -0.00345 , -0.024551,  0.      ],
       [-0.013892,  0.      , -0.033758,  0.      ,  0.      ],
       [ 0.      , -0.02907 ,  0.      ,  0.      , -0.005764],
       [ 0.      ,  0.      , -0.029803, -0.002743, -0.014301]])

In [99]:
corr_return=np.corrcoef(return_array1)
corr_return

array([[ 1.        ,  0.6019824 , -0.99072008, -0.0114095 ],
       [ 0.6019824 ,  1.        , -0.66621801,  0.38847344],
       [-0.99072008, -0.66621801,  1.        , -0.10970929],
       [-0.0114095 ,  0.38847344, -0.10970929,  1.        ]])

In [100]:
np.diag(corr_return)  # 矩阵的对角线

array([1., 1., 1., 1.])

In [101]:
np.triu(corr_return)  # 查看矩阵的上三角

array([[ 1.        ,  0.6019824 , -0.99072008, -0.0114095 ],
       [ 0.        ,  1.        , -0.66621801,  0.38847344],
       [ 0.        ,  0.        ,  1.        , -0.10970929],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [102]:
np.tril(corr_return) # 查看矩阵的下三角

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.6019824 ,  1.        ,  0.        ,  0.        ],
       [-0.99072008, -0.66621801,  1.        ,  0.        ],
       [-0.0114095 ,  0.38847344, -0.10970929,  1.        ]])

In [103]:
np.trace(corr_return) # 计算矩阵的迹

4.0

In [104]:
np.transpose(return_array1) # 将矩阵进行转置

array([[-3.5099e-02, -1.3892e-02,  5.8480e-03,  2.1242e-02],
       [ 1.7230e-01,  2.4334e-02, -2.9070e-02,  2.1330e-03],
       [-3.4500e-03, -3.3758e-02,  5.8310e-03, -2.9803e-02],
       [-2.4551e-02,  1.4622e-02,  5.7970e-03, -2.7430e-03],
       [ 3.9368e-02,  1.2800e-04, -5.7640e-03, -1.4301e-02]])

In [105]:
return_array1.T

array([[-3.5099e-02, -1.3892e-02,  5.8480e-03,  2.1242e-02],
       [ 1.7230e-01,  2.4334e-02, -2.9070e-02,  2.1330e-03],
       [-3.4500e-03, -3.3758e-02,  5.8310e-03, -2.9803e-02],
       [-2.4551e-02,  1.4622e-02,  5.7970e-03, -2.7430e-03],
       [ 3.9368e-02,  1.2800e-04, -5.7640e-03, -1.4301e-02]])

In [106]:
return_daily=np.dot(weight_array1,return_array1)
return_daily

array([ 0.00191555,  0.0242975 , -0.01773255, -0.0004062 , -0.0012306 ])

In [107]:
import numpy.linalg as la 
la.det(corr_return)  # 计算矩阵的行列式

0.0013592255406674886

In [108]:
la.inv(corr_return)  #计算矩阵的逆矩阵

array([[331.06581021,  14.32926162, 341.45344041,  35.67137476],
       [ 14.32926162,   2.81571109,  16.16465776,   0.84307398],
       [341.45344041,  16.16465776, 354.05388833,  36.45927606],
       [ 35.67137476,   0.84307398,  36.45927606,   5.07940225]])

In [109]:
la.eig(corr_return)  # 矩阵的特征值分解

(array([2.56393008e+00, 1.10387271e+00, 1.45202072e-03, 3.30745193e-01]),
 array([[ 0.5809005 ,  0.30884008,  0.6928313 ,  0.29522399],
        [ 0.52165002, -0.2829317 ,  0.03145369, -0.80426462],
        [-0.60196162, -0.19407993,  0.71656054, -0.29413634],
        [ 0.16756515, -0.88707409,  0.07440733,  0.42365674]]))

In [110]:
la.svd(corr_return)  # 矩阵的奇异值分解

(array([[-0.5809005 ,  0.30884008,  0.29522399,  0.6928313 ],
        [-0.52165002, -0.2829317 , -0.80426462,  0.03145369],
        [ 0.60196162, -0.19407993, -0.29413634,  0.71656054],
        [-0.16756515, -0.88707409,  0.42365674,  0.07440733]]),
 array([2.56393008e+00, 1.10387271e+00, 3.30745193e-01, 1.45202072e-03]),
 array([[-0.5809005 , -0.52165002,  0.60196162, -0.16756515],
        [ 0.30884008, -0.2829317 , -0.19407993, -0.88707409],
        [ 0.29522399, -0.80426462, -0.29413634,  0.42365674],
        [ 0.6928313 ,  0.03145369,  0.71656054,  0.07440733]]))

## 2.5 基于特定统计分布的随机抽样

In [111]:
import numpy.random as npr
I=10000
mean1=1.5
std1=2.5
x_norm=npr.normal(loc=mean1,scale=std1,size=I)
print('从正态分布中随机抽样的均值为:\n',x_norm.mean())
print('从正态分布中随机抽样的标准差为:\n',x_norm.std())

从正态分布中随机抽样的均值为:
 1.5155697204025662
从正态分布中随机抽样的标准差为:
 2.5067344491503145


In [113]:
# 从标准正态分布中抽取随机数
x_snorml1=npr.randn(I)  
x_snorml2=npr.standard_normal(size=I)
mean2=0
std2=1
x_snorm3=npr.normal(loc=mean2,scale=std2,size=I)
print('运用randn函数从标准正态分布中抽样的均值',x_snorml1.mean())
print('运用randn函数从标准正态分布中抽样的标准差',x_snorml1.std())
print('运用standard_normal函数从标准正态分布中抽样的均值',x_snorml2.mean())
print('运用standard_normal函数从标准正态分布中抽样的标准差',x_snorml2.std())
print('运用normal函数从标准正态分布中抽样的均值',x_snorm3.mean())
print('运用normal函数从标准正态分布中抽样的均值',x_snorm3.std())

运用randn函数从标准正态分布中抽样的均值 -0.005509972919991859
运用randn函数从标准正态分布中抽样的标准差 1.0163887926826873
运用standard_normal函数从标准正态分布中抽样的均值 -0.00045179740509185853
运用standard_normal函数从标准正态分布中抽样的标准差 0.9971778789458143
运用normal函数从标准正态分布中抽样的均值 -0.003045843583597555
运用normal函数从标准正态分布中抽样的均值 1.001454097400369


In [114]:
# 对数正态分布的随机抽样
mean3=0.4
std3=1.2
x_logn=npr.lognormal(mean=mean3,sigma=std3,size=I)
print('从对数正态分布中抽样的均值',x_logn.mean())
print('从对数正态分布中抽样的标准差',x_logn.std())

从对数正态分布中抽样的均值 3.063020361097541
从对数正态分布中抽样的标准差 5.412198547523007


In [115]:
# 基于卡方分布的随机抽样
freedom1=6
freedom2=98
x_chil1=npr.chisquare(df=freedom1,size=I)
x_chil2=npr.chisquare(df=freedom2,size=I)
print('从自由度是6的卡方分布中抽样的均值为',x_chil1.mean())
print('从自由度是6的卡方分布中抽样的标准差为',x_chil1.std())
print('从自由度是98的卡方分布中抽样的均值为',x_chil2.mean())
print('从自由度是98的卡方分布中抽样的标准差为',x_chil2.std())

从自由度是6的卡方分布中抽样的均值为 6.000811396819553
从自由度是6的卡方分布中抽样的标准差为 3.462620099227775
从自由度是98的卡方分布中抽样的均值为 98.12398452142806
从自由度是98的卡方分布中抽样的标准差为 13.972550994692273


In [116]:
# 基于学生t分布的随机抽样
freedom3=3
freedom4=130
x_t1=npr.standard_t(df=freedom3,size=I)
x_t2=npr.standard_t(df=freedom4,size=I)
print('从自由度是3的学生t分布中抽样的均值为',x_t1.mean())
print('从自由度是3的学生t分布中抽样的标准差为',x_t1.std())
print('从自由度是130的学生t分布中抽样的均值为',x_t2.mean())
print('从自由度是130的学生t分布中抽样的标准差为',x_t2.std())

从自由度是3的学生t分布中抽样的均值为 0.002927426169901787
从自由度是3的学生t分布中抽样的标准差为 1.6632748332928098
从自由度是130的学生t分布中抽样的均值为 -0.012835590615785113
从自由度是130的学生t分布中抽样的标准差为 1.0087925408095557


In [118]:
# 基于F分布的随机抽样
freedom5=4
freedom6=10
x_f=npr.f(dfnum=freedom5,dfden=freedom6,size=I)
print('从F分布中抽样的均值为',x_f.mean())
print('从F分布中抽样的标准差为',x_f.std())

从F分布中抽样的均值为 1.2478961642178716
从F分布中抽样的标准差为 1.229073362255744


In [117]:
# 基于贝塔分布的随机抽样、
a1=3
b1=7
x_beta=npr.beta(a=a1,b=b1,size=I)
print('从贝塔分布中抽样的均值为',x_beta.mean())
print('从贝塔分布中抽样的标准差为',x_beta.std())

从贝塔分布中抽样的均值为 0.30004009471480947
从贝塔分布中抽样的标准差为 0.13706868969736982


In [119]:
# 基于伽马分布的随机抽样
a2=2
b2=8
x_gamma=npr.gamma(shape=a2,scale=b2,size=I)
print('从伽马分布中抽样的均值为',x_gamma.mean())
print('从伽马分布中抽样的标准差为',x_gamma.std())

从伽马分布中抽样的均值为 16.042737726152154
从伽马分布中抽样的标准差为 11.3419870908981


## 2.6 现金流量模型

In [126]:
import numpy_financial as npf
npf.__version__

'1.0.0'

In [127]:
V0=2e7 # 初始投资金额
V1=3e6 # 每年固定金额投资
T=5  # 投资期限（年）
r=0.08 # 年华投资回报率
FV1=npf.fv(rate=r,nper=T,pmt=-V1,pv=-V0,when='end')
print('计算得到项目终值（期间追加投资发生在每年年末',round(FV1,2))

计算得到项目终值（期间追加投资发生在每年年末 46986364.42


In [128]:
FV2=npf.fv(rate=r,nper=T,pmt=-V1,pv=-V0,when='begin')
print('计算得到项目终值（期间追加投资发生在每年年末',round(FV2,2))

计算得到项目终值（期间追加投资发生在每年年末 48394348.65


In [129]:
FV_diff=FV2-FV1
print('期间追加投资发生时点不同而导致项目终值的差异',round(FV_diff,2))

期间追加投资发生时点不同而导致项目终值的差异 1407984.23


In [130]:
V1 = 2e6  
Vt = 2.5e7  
T = 6
R = 0.06
PV1 = npf.pv(rate=R, nper=T, pmt=V1, fv=Vt, when=0)
print('计算得到项目终值（期间现金流发生在每年年末', round(PV1, 2))
PV2 = npf.pv(rate=R, nper=T, pmt=V1, fv=Vt, when=1)
print('计算得到项目终值（期间现金流发生在每年年初', round(PV2, 2))
PV_diff = PV2 - PV1
print('期间追加投资发生时点不同而导致项目终值的差异', round(PV_diff, 2))

计算得到项目终值（期间现金流发生在每年年末 -27458662.16
计算得到项目终值（期间现金流发生在每年年初 -28048741.08
期间追加投资发生时点不同而导致项目终值的差异 -590078.92


In [131]:
# 净现值与内含报酬率
R1=0.09
cashflow=np.array([-2.8e7,7e6,8e6,9e6,1e7])
NPV1=npf.npv(rate=R1,values=cashflow)
print(NPV1)
R2=0.06
NPV2=npf.npv(rate=R2,values=cashflow)
print(NPV2)

-810638.2740421267
1201255.2846905012


In [132]:
IRR=npf.irr(values=cashflow)
IRR

0.07750274098507792

In [133]:
# 住房按揭贷快的等额本息还款
prin_loan=5e6
tenor_loan=5*12
rate_loan=0.06/12
payment=npf.pmt(rate=rate_loan,nper=tenor_loan,pv=prin_loan,fv=0,when='end')
payment

-96664.00764714135

In [134]:
tenor_list=np.arange(tenor_loan)+1
payment_interset=npf.ipmt(rate=rate_loan,per=tenor_list,nper=tenor_loan,pv=prin_loan,fv=0,when='end')
payment_interset

array([-25000.        , -24641.67996176, -24281.56832334, -23919.65612672,
       -23555.93436912, -23190.39400273, -22823.0259345 , -22453.82102594,
       -22082.77009283, -21709.86390506, -21335.09318635, -20958.44861405,
       -20579.92081888, -20199.50038474, -19817.17784843, -19432.94369944,
       -19046.7883797 , -18658.70228336, -18268.67575654, -17876.69909709,
       -17482.76255434, -17086.85632887, -16688.97057228, -16289.09538691,
       -15887.22082561, -15483.3368915 , -15077.43353772, -14669.50066718,
       -14259.52813228, -13847.5057347 , -13433.42322514, -13017.27030303,
       -12599.03661631, -12178.71176115, -11756.28528172, -11331.7466699 ,
       -10905.08536501, -10476.2907536 , -10045.35216913,  -9612.25889174,
        -9177.00014797,  -8739.56511047,  -8299.94289779,  -7858.12257404,
        -7414.09314867,  -6967.84357618,  -6519.36275583,  -6068.63953137,
        -5615.66269079,  -5160.42096601,  -4702.9030326 ,  -4243.09750953,
        -3780.99295884,  

In [135]:
payment_principle=npf.ppmt(rate=rate_loan,per=tenor_list,nper=tenor_loan,pv=prin_loan,fv=0,when='end')
payment_principle

array([-71664.00764714, -72022.32768538, -72382.4393238 , -72744.35152042,
       -73108.07327803, -73473.61364442, -73840.98171264, -74210.1866212 ,
       -74581.23755431, -74954.14374208, -75328.91446079, -75705.55903309,
       -76084.08682826, -76464.5072624 , -76846.82979871, -77231.0639477 ,
       -77617.21926744, -78005.30536378, -78395.3318906 , -78787.30855005,
       -79181.2450928 , -79577.15131827, -79975.03707486, -80374.91226023,
       -80776.78682153, -81180.67075564, -81586.57410942, -81994.50697997,
       -82404.47951487, -82816.50191244, -83230.584422  , -83646.73734411,
       -84064.97103083, -84485.29588599, -84907.72236542, -85332.26097724,
       -85758.92228213, -86187.71689354, -86618.65547801, -87051.7487554 ,
       -87487.00749918, -87924.44253667, -88364.06474935, -88805.8850731 ,
       -89249.91449847, -89696.16407096, -90144.64489131, -90595.36811577,
       -91048.34495635, -91503.58668113, -91961.10461454, -92420.91013761,
       -92883.0146883 , -